spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot1
    username: root
    password: 123
    hikari:
      auto-commit: true


#spring.datasource.hikari.minimum-idle

