spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
#    spring.cloud.config.label：配置仓库的分支
      label: master
      server:
        git:
#        如果使用 GitLab 作为仓库的话，git.uri 需要在结尾加上 .git，GitHub 则不用
#        spring.cloud.config.server.git.uri：配置 Git 仓库地址（GitHub、GitLab、码云 ...）
          uri: https://github.com/topsale/spring-cloud-config
#          spring.cloud.config.server.git.search-paths：配置仓库路径（存放配置文件的目录）
          search-paths: respo
#          spring.cloud.config.server.git.username：访问 Git 仓库的账号
#          spring.cloud.config.server.git.password：访问 Git 仓库的密码
          username:
          password:

server:
#不可以改，如果要改必须写一个bootstrap.properties，写server.port=11061
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/